# Generated by Django 3.0.5 on 2020-04-24 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Section')),
            ],
        ),
    ]
