# Generated by Django 3.0.5 on 2020-04-26 12:19

from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrfNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Section')),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
